/**
 * ============================================================
 * Audlex — Bilingual content for Document Generators
 * ============================================================
 *
 * Translation maps for document template metadata, section titles,
 * and document content used by generators.ts.
 */

export type Locale = "es" | "en";

// ============================================================
// DOCUMENT TEMPLATE METADATA (title, description)
// ============================================================

export const templateTitles: Record<string, Record<Locale, string>> = {
  impact_assessment: {
    es: "Evaluación de Impacto de Derechos Fundamentales (FRIA)",
    en: "Fundamental Rights Impact Assessment (FRIA)",
  },
  risk_management: {
    es: "Plan de Gestión de Riesgos",
    en: "Risk Management Plan",
  },
  technical_file: {
    es: "Ficha Técnica del Sistema de IA",
    en: "AI System Technical File",
  },
  conformity_declaration: {
    es: "Declaración de Conformidad UE",
    en: "EU Declaration of Conformity",
  },
  human_oversight: {
    es: "Protocolo de Supervisión Humana",
    en: "Human Oversight Protocol",
  },
  transparency_notice: {
    es: "Aviso de Transparencia",
    en: "Transparency Notice",
  },
  data_governance: {
    es: "Plan de Gobernanza de Datos",
    en: "Data Governance Plan",
  },
  post_market_monitoring: {
    es: "Plan de Monitorización Post-Comercialización",
    en: "Post-Market Monitoring Plan",
  },
  ai_usage_policy: {
    es: "Política de Uso de IA de la Organización",
    en: "Organisation AI Usage Policy",
  },
  ai_inventory: {
    es: "Inventario de Sistemas de IA",
    en: "AI Systems Inventory",
  },
};

export const templateDescriptions: Record<string, Record<Locale, string>> = {
  impact_assessment: {
    es: "Evaluación del impacto del sistema IA en los derechos fundamentales de las personas afectadas",
    en: "Assessment of the AI system's impact on the fundamental rights of affected persons",
  },
  risk_management: {
    es: "Sistema de gestión de riesgos para el ciclo de vida del sistema de IA",
    en: "Risk management system for the AI system lifecycle",
  },
  technical_file: {
    es: "Documentación técnica completa según Anexo IV del EU AI Act",
    en: "Complete technical documentation per Annex IV of the EU AI Act",
  },
  conformity_declaration: {
    es: "Declaración formal de que el sistema cumple con los requisitos del EU AI Act",
    en: "Formal declaration that the system complies with the EU AI Act requirements",
  },
  human_oversight: {
    es: "Procedimientos para la supervisión humana efectiva del sistema de IA",
    en: "Procedures for effective human oversight of the AI system",
  },
  transparency_notice: {
    es: "Información que debe proporcionarse a los usuarios y personas afectadas",
    en: "Information to be provided to users and affected persons",
  },
  data_governance: {
    es: "Prácticas de gobernanza de datos para los conjuntos de datos de entrenamiento y validación",
    en: "Data governance practices for training and validation datasets",
  },
  post_market_monitoring: {
    es: "Sistema de seguimiento posterior a la comercialización del sistema de IA",
    en: "Post-market surveillance system for the AI system",
  },
  ai_usage_policy: {
    es: "Política interna que regula el uso de sistemas de IA en la organización",
    en: "Internal policy governing the use of AI systems in the organisation",
  },
  ai_inventory: {
    es: "Registro completo de todos los sistemas de IA utilizados",
    en: "Complete registry of all AI systems in use",
  },
};

// ============================================================
// DOCUMENT-TO-MARKDOWN LABELS
// ============================================================

export const markdownLabels = {
  organization: { es: "Organización", en: "Organisation" },
  cifNif: { es: "CIF/NIF", en: "Tax ID" },
  aiSystem: { es: "Sistema de IA", en: "AI System" },
  category: { es: "Categoría", en: "Category" },
  riskLevel: { es: "Nivel de riesgo", en: "Risk level" },
  generatedDate: { es: "Fecha de generación", en: "Generation date" },
  version: { es: "Versión", en: "Version" },
  normativeRef: { es: "Referencia normativa", en: "Normative reference" },
  footer: {
    es: "Documento generado por Audlex — Plataforma de Cumplimiento EU AI Act",
    en: "Document generated by Audlex — EU AI Act Compliance Platform",
  },
  footerDisclaimer: {
    es: "Este documento es orientativo y debe ser revisado por un profesional cualificado.",
    en: "This document is for guidance purposes and should be reviewed by a qualified professional.",
  },
} as const;

// ============================================================
// COMMON LABELS USED ACROSS GENERATORS
// ============================================================

export const commonLabels = {
  notSpecified: { es: "No especificado", en: "Not specified" },
  notEstimated: { es: "No estimado", en: "Not estimated" },
  noDescription: { es: "Sin descripción adicional proporcionada.", en: "No additional description provided." },
  pendingClassification: { es: "Pendiente de clasificación", en: "Pending classification" },
  pendingEval: { es: "Pendiente de evaluación", en: "Pending evaluation" },
  complete: { es: "[Completar]", en: "[Complete]" },
  yes: { es: "Sí", en: "Yes" },
  no: { es: "No", en: "No" },
  unclassified: { es: "sin clasificar", en: "unclassified" },
  country: { es: "España", en: "Spain" },
  deploymentDate: { es: "Fecha de despliegue", en: "Deployment date" },
  status: { es: "Estado", en: "Status" },
} as const;

// ============================================================
// EXPORT ROUTE LABELS
// ============================================================

export const exportLabels = {
  docxDescription: {
    es: "Documento de compliance EU AI Act generado por Audlex",
    en: "EU AI Act compliance document generated by Audlex",
  },
  pdfFooter: {
    es: "Documento generado automáticamente por Audlex — Compliance EU AI Act (Reglamento UE 2024/1689)",
    en: "Document automatically generated by Audlex — EU AI Act Compliance (Regulation EU 2024/1689)",
  },
  docxFooter: {
    es: "Generado por Audlex | ",
    en: "Generated by Audlex | ",
  },
} as const;
