/**
 * ============================================================
 * Audlex — PDF Export Service
 * ============================================================
 * 
 * Generate professional PDFs from markdown documents:
 * - Headers and footers with branding
 * - Table of contents
 * - Page numbers
 * - Proper pagination
 * - Styled tables and sections
 */

import { jsPDF } from "jspdf";
import type { GeneratedDocument } from "../documents/generators";

interface PDFOptions {
  includeTableOfContents?: boolean;
  includeCoverPage?: boolean;
  watermark?: string;
  footer?: string;
  pageNumbers?: boolean;
}

export class PDFGenerator {
  private doc: jsPDF;
  private currentY: number = 20;
  private pageHeight: number = 297; // A4 height in mm
  private pageWidth: number = 210; // A4 width in mm
  private margin: number = 20;
  private lineHeight: number = 7;
  private pageNumber: number = 1;

  constructor() {
    this.doc = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });
  }

  /**
   * Generate PDF from document
   */
  async generateFromDocument(
    document: GeneratedDocument,
    options: PDFOptions = {}
  ): Promise<Blob> {
    const {
      includeTableOfContents = true,
      includeCoverPage = true,
      pageNumbers = true,
      footer = "Generated by Audlex · www.audlex.com",
    } = options;

    // Cover page
    if (includeCoverPage) {
      this.addCoverPage(document);
      this.addPage();
    }

    // Table of contents
    if (includeTableOfContents) {
      this.addTableOfContents(document);
      this.addPage();
    }

    // Document sections
    document.sections.forEach((section, index) => {
      this.addSection(section, 1);
    });

    // Add page numbers and footers
    if (pageNumbers || footer) {
      this.addPageNumbersAndFooters(footer, pageNumbers);
    }

    return this.doc.output("blob");
  }

  /**
   * Add cover page
   */
  private addCoverPage(document: GeneratedDocument) {
    // Logo/Brand area
    this.doc.setFillColor(37, 99, 235); // brand-600
    this.doc.rect(0, 0, this.pageWidth, 60, "F");

    // Title
    this.doc.setTextColor(255, 255, 255);
    this.doc.setFontSize(26);
    this.doc.setFont("helvetica", "bold");
    
    const titleLines = this.doc.splitTextToSize(document.title, this.pageWidth - 40);
    this.currentY = 30;
    titleLines.forEach((line: string) => {
      this.doc.text(line, this.pageWidth / 2, this.currentY, { align: "center" });
      this.currentY += 10;
    });

    // Reset color
    this.doc.setTextColor(0, 0, 0);

    // Metadata section
    this.currentY = 100;
    this.doc.setFontSize(12);
    this.doc.setFont("helvetica", "normal");

    const metadata = [
      ["Organization:", document.organization.name],
      ["Version:", document.version],
      ["Generated:", new Date(document.generatedAt).toLocaleDateString()],
      ...(document.system ? [["AI System:", document.system.name]] : []),
      ...(document.riskLevel ? [["Risk Level:", document.riskLevel.toUpperCase()]] : []),
      ["Article Reference:", document.metadata.articleReference],
      ["Deadline:", document.metadata.deadline],
    ];

    metadata.forEach(([label, value]) => {
      this.doc.setFont("helvetica", "bold");
      this.doc.text(label, this.margin, this.currentY);
      this.doc.setFont("helvetica", "normal");
      this.doc.text(value, this.margin + 60, this.currentY);
      this.currentY += 8;
    });

    // Compliance statement
    this.currentY = 220;
    this.doc.setFillColor(243, 244, 246); // gray-100
    this.doc.rect(this.margin, this.currentY, this.pageWidth - 2 * this.margin, 50, "F");
    
    this.doc.setFontSize(10);
    this.doc.setFont("helvetica", "italic");
    const disclaimer = "This document has been generated automatically by Audlex in compliance with Regulation (EU) 2024/1689 on Artificial Intelligence (AI Act). It is intended for official submission to competent authorities and audit purposes.";
    const disclaimerLines = this.doc.splitTextToSize(disclaimer, this.pageWidth - 2 * this.margin - 10);
    
    this.currentY += 8;
    disclaimerLines.forEach((line: string) => {
      this.doc.text(line, this.margin + 5, this.currentY);
      this.currentY += 5;
    });
  }

  /**
   * Add table of contents
   */
  private addTableOfContents(document: GeneratedDocument) {
    this.doc.setFont("helvetica", "bold");
    this.doc.setFontSize(18);
    this.doc.text("Table of Contents", this.margin, this.currentY);
    
    this.currentY += 15;
    this.doc.setFontSize(11);
    
    document.sections.forEach((section, index) => {
      if (this.currentY > this.pageHeight - this.margin) {
        this.addPage();
      }

      this.doc.setFont("helvetica", "bold");
      this.doc.text(`${index + 1}. ${section.title}`, this.margin, this.currentY);
      this.currentY += 6;

      section.subsections?.forEach((subsection, subIndex) => {
        if (this.currentY > this.pageHeight - this.margin) {
          this.addPage();
        }
        this.doc.setFont("helvetica", "normal");
        this.doc.text(`   ${index + 1}.${subIndex + 1}. ${subsection.title}`, this.margin + 5, this.currentY);
        this.currentY += 5;
      });

      this.currentY += 3;
    });
  }

  /**
   * Add section to PDF
   */
  private addSection(section: any, level: number) {
    // Section title
    const fontSize = level === 1 ? 16 : level === 2 ? 14 : 12;
    this.doc.setFontSize(fontSize);
    this.doc.setFont("helvetica", "bold");

    if (this.currentY > this.pageHeight - this.margin - 20) {
      this.addPage();
    }

    this.doc.text(section.title, this.margin, this.currentY);
    this.currentY += fontSize / 2 + 2;

    // Section content
    if (section.content) {
      this.doc.setFontSize(11);
      this.doc.setFont("helvetica", "normal");
      
      const contentLines = this.doc.splitTextToSize(
        section.content,
        this.pageWidth - 2 * this.margin
      );

      contentLines.forEach((line: string) => {
        if (this.currentY > this.pageHeight - this.margin) {
          this.addPage();
        }
        this.doc.text(line, this.margin, this.currentY);
        this.currentY += this.lineHeight;
      });

      this.currentY += 3;
    }

    // Subsections
    if (section.subsections) {
      section.subsections.forEach((subsection: any) => {
        this.addSection(subsection, level + 1);
      });
    }
  }

  /**
   * Add new page
   */
  private addPage() {
    this.doc.addPage();
    this.currentY = this.margin;
    this.pageNumber++;
  }

  /**
   * Add page numbers and footers
   */
  private addPageNumbersAndFooters(footer: string, includePageNumbers: boolean) {
    const pageCount = this.doc.getNumberOfPages();

    for (let i = 1; i <= pageCount; i++) {
      this.doc.setPage(i);
      this.doc.setFontSize(9);
      this.doc.setFont("helvetica", "normal");
      this.doc.setTextColor(128, 128, 128);

      // Footer text
      this.doc.text(footer, this.pageWidth / 2, this.pageHeight - 10, {
        align: "center",
      });

      // Page number
      if (includePageNumbers && i > 1) {
        // Skip cover page
        this.doc.text(
          `Page ${i - 1} of ${pageCount - 1}`,
          this.pageWidth - this.margin,
          this.pageHeight - 10,
          { align: "right" }
        );
      }
    }
  }
}

/**
 * Quick export function
 */
export async function exportDocumentToPDF(
  document: GeneratedDocument,
  options?: PDFOptions
): Promise<Blob> {
  const generator = new PDFGenerator();
  return generator.generateFromDocument(document, options);
}

/**
 * Download PDF to browser
 */
export function downloadPDF(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
